'use strict';
const express = require('express');
const router = express.Router();
const pool = require('../../memory/db/pool');

// GET /api/dashboard/ceo
// Phase F.2 - CEO Executive Dashboard - batched queries (max 5 concurrent)
router.get('/ceo', async function(req, res) {
  var now = new Date();
    try {
        // Batch 1: Core KPIs + Hot Leads + Channel Data (5 queries)
            var b1 = await Promise.allSettled([
                  pool.query("SELECT (SELECT COUNT(*) FROM lead_memory) as total_leads,(SELECT COUNT(*) FROM lead_memory WHERE created_at>=CURRENT_DATE) as leads_today,(SELECT COUNT(*) FROM lead_memory WHERE created_at>=date_trunc('week',NOW())) as leads_this_week,(SELECT COUNT(*) FROM lead_memory WHERE created_at>=date_trunc('month',NOW())) as leads_this_month,(SELECT COUNT(*) FROM lead_qualification WHERE category='hot') as hot_leads,(SELECT COUNT(*) FROM lead_qualification WHERE calculation_status='completed') as qualified_leads,(SELECT COUNT(*) FROM ai_decisions WHERE created_at>=CURRENT_DATE) as ai_decisions_today,(SELECT COUNT(*) FROM conversation_analysis WHERE created_at>=CURRENT_DATE) as active_conversations_today"),
                        pool.query("SELECT lm.id,lm.full_name,lm.brand_name,lm.phone,lm.email,lm.source,lm.created_at,lq.category,lq.onboarding_probability,lq.score,lq.confidence_score,lq.assigned_rep FROM lead_memory lm LEFT JOIN lead_qualification lq ON lq.lead_memory_id=lm.id WHERE lq.category='hot' ORDER BY lq.score DESC NULLS LAST LIMIT 20"),
                              pool.query("SELECT source,COUNT(*) as total_leads,COUNT(*) FILTER(WHERE lq.category='hot') as hot,COUNT(*) FILTER(WHERE lq.category='warm') as warm,COUNT(*) FILTER(WHERE lq.category='cold') as cold FROM lead_memory lm LEFT JOIN lead_qualification lq ON lq.lead_memory_id=lm.id GROUP BY source ORDER BY total_leads DESC"),
                                    pool.query("SELECT le.id,le.event_type,le.created_at,lm.full_name,lm.brand_name,lm.source FROM lead_events le LEFT JOIN lead_memory lm ON lm.id=le.lead_memory_id ORDER BY le.created_at DESC LIMIT 20"),
                                          pool.query("SELECT COUNT(*) as total_chats,COUNT(*) FILTER(WHERE created_at>=CURRENT_DATE) as today_chats,COUNT(*) FILTER(WHERE status='open') as open_chats FROM salesiq_chats")
                                              ]);
                                              
                                                  // Batch 2: Qualification funnel + decisions + leaderboard + learning + costs (5 queries)
                                                      var b2 = await Promise.allSettled([
                                                            pool.query("SELECT category,COUNT(*) as count FROM lead_qualification GROUP BY category ORDER BY CASE category WHEN 'hot' THEN 1 WHEN 'warm' THEN 2 WHEN 'cold' THEN 3 WHEN 'dead' THEN 4 ELSE 5 END"),
                                                                  pool.query("SELECT action_type,status,COUNT(*) as count FROM ai_decisions GROUP BY action_type,status ORDER BY count DESC LIMIT 20"),
                                                                        pool.query("SELECT lm.source,COUNT(*) as total,COUNT(*) FILTER(WHERE lq.category='hot') as hot,COUNT(*) FILTER(WHERE lq.category='warm') as warm,AVG(lq.onboarding_probability) as avg_probability,AVG(lq.confidence_score) as avg_confidence FROM lead_memory lm LEFT JOIN lead_qualification lq ON lq.lead_memory_id=lm.id GROUP BY lm.source ORDER BY hot DESC"),
                                                                              pool.query("SELECT COUNT(*) as total_predictions,COUNT(*) FILTER(WHERE evaluation_status='evaluated') as evaluated,COUNT(*) FILTER(WHERE created_at>=CURRENT_DATE) as today,AVG(confidence) as avg_confidence,COUNT(*) FILTER(WHERE evaluation_status='evaluated' AND outcome_matched=true) as correct FROM ai_predictions"),
                                                                                    pool.query("SELECT module_name,SUM(cost_usd) as total_cost,COUNT(*) as calls,AVG(latency_ms) as avg_latency FROM platform_cost_events WHERE created_at>=CURRENT_DATE GROUP BY module_name ORDER BY total_cost DESC")
                                                                                        ]);
                                                                                        
                                                                                            // Batch 3: Platform health + queues + agents + alerts + DLQ (5 queries)
                                                                                                var b3 = await Promise.allSettled([
                                                                                                      pool.query("SELECT DISTINCT ON(module_name) module_name,status,health_score,checked_at as last_checked_at FROM platform_module_health ORDER BY module_name,checked_at DESC"),
                                                                                                            pool.query("SELECT queue_name,status,pending_jobs,running_jobs,completed_jobs,failed_jobs,worker_count FROM platform_queue_status ORDER BY queue_name"),
                                                                                                                  pool.query("SELECT agent_name,status,last_run_at,runs_completed,runs_failed,avg_runtime_ms FROM agent_performance ORDER BY agent_name"),
                                                                                                                        pool.query("SELECT module_name,error_type,severity,message,created_at FROM platform_errors WHERE resolution_status='open' ORDER BY CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 ELSE 3 END,created_at DESC LIMIT 15"),
                                                                                                                              pool.query("SELECT job_type,COUNT(*) as count,MAX(created_at) as last_failure FROM job_dead_letter WHERE job_type NOT LIKE 'chaos%' GROUP BY job_type ORDER BY count DESC")
                                                                                                                                  ]);
                                                                                                                                  
                                                                                                                                      // Batch 4: Forecasts + conversations + workflows + lm time breakdown (4 queries)
                                                                                                                                          var b4 = await Promise.allSettled([
                                                                                                                                                pool.query("SELECT forecast_value,forecast_date,scenario,confidence_score,created_at FROM revenue_forecasts ORDER BY created_at DESC LIMIT 5"),
                                                                                                                                                      pool.query("SELECT lm.source,COUNT(ca.id) as conversations,AVG(ca.confidence_score) as avg_confidence FROM conversation_analysis ca LEFT JOIN lead_memory lm ON lm.id=ca.lead_memory_id WHERE ca.analysis_status='completed' GROUP BY lm.source"),
                                                                                                                                                            pool.query("SELECT status,COUNT(*) as count FROM workflow_execution GROUP BY status"),
                                                                                                                                                                  pool.query("SELECT (SELECT COUNT(*) FROM lead_memory WHERE created_at>=CURRENT_DATE) as today,(SELECT COUNT(*) FROM lead_memory WHERE created_at>=NOW()-INTERVAL '7 days') as last_7d,(SELECT COUNT(*) FROM lead_memory) as all_time")
                                                                                                                                                                      ]);
                                                                                                                                                                      
                                                                                                                                                                          function s(batch,idx){return batch[idx]&&batch[idx].status==='fulfilled'?batch[idx].value.rows:[];}
                                                                                                                                                                              function s1(batch,idx){return batch[idx]&&batch[idx].status==='fulfilled'&&batch[idx].value.rows.length>0?batch[idx].value.rows[0]:{};}
                                                                                                                                                                              
                                                                                                                                                                                  var kpis=s1(b1,0),hotLeads=s(b1,1),channelRaw=s(b1,2),activityFeed=s(b1,3),salesiq=s1(b1,4);
                                                                                                                                                                                      var funnel=s(b2,0),decisions=s(b2,1),aiLeaderboard=s(b2,2),learning=s1(b2,3),costs=s(b2,4);
                                                                                                                                                                                          var modules=s(b3,0),queues=s(b3,1),agents=s(b3,2),alerts=s(b3,3),dlq=s(b3,4);
                                                                                                                                                                                              var forecasts=s(b4,0),convByChannel=s(b4,1),workflows=s(b4,2),leadTime=s1(b4,3);
                                                                                                                                                                                              
                                                                                                                                                                                                  var channelMap={};channelRaw.forEach(function(r){channelMap[r.source]=r;});
                                                                                                                                                                                                      var convMap={};convByChannel.forEach(function(r){convMap[r.source]=r;});
                                                                                                                                                                                                      
                                                                                                                                                                                                          var aiChannelDefs=[
                                                                                                                                                                                                                {channel:'Meta AI',sources:['meta','meta_ad','facebook','Meta','META']},
                                                                                                                                                                                                                      {channel:'SalesIQ AI',sources:['salesiq','website','chat','SalesIQ','Website','SALESIQ']},
                                                                                                                                                                                                                            {channel:'Retell AI',sources:['retell','call','phone','Retell','RETELL']},
                                                                                                                                                                                                                                  {channel:'Email AI',sources:['email','Email','EMAIL']},
                                                                                                                                                                                                                                        {channel:'SMS AI',sources:['sms','twilio','SMS','Twilio','TWILIO']}
                                                                                                                                                                                                                                            ];
                                                                                                                                                                                                                                                var aiChannelHealth=aiChannelDefs.map(function(ch){
                                                                                                                                                                                                                                                      var td=0,hot=0,warm=0,cold=0,convs=0,conf=null;
                                                                                                                                                                                                                                                            ch.sources.forEach(function(s){
                                                                                                                                                                                                                                                                    if(channelMap[s]){td+=parseInt(channelMap[s].total_leads||0);hot+=parseInt(channelMap[s].hot||0);warm+=parseInt(channelMap[s].warm||0);cold+=parseInt(channelMap[s].cold||0);}
                                                                                                                                                                                                                                                                            if(convMap[s]){convs+=parseInt(convMap[s].conversations||0);if(convMap[s].avg_confidence)conf=parseFloat(convMap[s].avg_confidence);}
                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                        return {channel:ch.channel,status:td>0?'active':'no_data',total_leads:td,hot_leads:hot,warm_leads:warm,cold_leads:cold,conversations:convs,qualified:hot+warm,conversion_pct:td>0?Math.round((hot+warm)/td*1000)/10:0,avg_confidence:conf};
                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                var copilotItems=[];
                                                                                                                                                                                                                                                                                                    var hl=parseInt(kpis.hot_leads||0),ad=parseInt(kpis.ai_decisions_today||0),lt=parseInt(kpis.leads_today||0);
                                                                                                                                                                                                                                                                                                        if(hl>0)copilotItems.push(hl+' hot leads require attention today');
                                                                                                                                                                                                                                                                                                            if(ad>0)copilotItems.push(ad+' AI decisions made today');
                                                                                                                                                                                                                                                                                                                if(lt>0)copilotItems.push(lt+' new leads captured today');
                                                                                                                                                                                                                                                                                                                    if(alerts.length>0)copilotItems.push(alerts.length+' platform alert(s) require attention');
                                                                                                                                                                                                                                                                                                                        var openDlq=dlq.reduce(function(sum,r){return sum+parseInt(r.count||0);},0);
                                                                                                                                                                                                                                                                                                                            if(openDlq>0)copilotItems.push(openDlq+' production jobs in dead letter queue');
                                                                                                                                                                                                                                                                                                                                var tc=costs.reduce(function(sum,r){return sum+parseFloat(r.total_cost||0);},0);
                                                                                                                                                                                                                                                                                                                                    if(tc>0)copilotItems.push("Today's AI cost: $"+tc.toFixed(4));
                                                                                                                                                                                                                                                                                                                                        if(copilotItems.length===0)copilotItems.push('Platform operating normally - no immediate actions required');
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                            res.json({
                                                                                                                                                                                                                                                                                                                                                  success:true,retrieved_at:now.toISOString(),
                                                                                                                                                                                                                                                                                                                                                        kpis:{total_leads:parseInt(kpis.total_leads||0),leads_today:lt,leads_this_week:parseInt(kpis.leads_this_week||0),leads_this_month:parseInt(kpis.leads_this_month||0),hot_leads:hl,qualified_leads:parseInt(kpis.qualified_leads||0),ai_decisions_today:ad,active_conversations_today:parseInt(kpis.active_conversations_today||0),salesiq_open_chats:parseInt(salesiq.open_chats||0),lead_time:leadTime},
                                                                                                                                                                                                                                                                                                                                                              hot_leads:hotLeads,ai_channel_health:aiChannelHealth,channel_raw:channelRaw,activity_feed:activityFeed,ai_leaderboard:aiLeaderboard,funnel:funnel,
                                                                                                                                                                                                                                                                                                                                                                    alerts:alerts,agents:agents,queues:queues,
                                                                                                                                                                                                                                                                                                                                                                          learning:{total_predictions:parseInt(learning.total_predictions||0),evaluated:parseInt(learning.evaluated||0),today:parseInt(learning.today||0),avg_confidence:parseFloat(learning.avg_confidence||0),correct:parseInt(learning.correct||0),accuracy:parseInt(learning.evaluated)>0?Math.round(parseInt(learning.correct)/parseInt(learning.evaluated)*1000)/10:0},
                                                                                                                                                                                                                                                                                                                                                                                costs:costs,decisions:decisions,modules:modules,workflows:workflows,forecasts:forecasts,copilot_briefing:copilotItems,dlq:dlq
                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                      }catch(err){
                                                                                                                                                                                                                                                                                                                                                                                          console.error('[CEO Dashboard]',err.message);
                                                                                                                                                                                                                                                                                                                                                                                              res.status(500).json({success:false,error:err.message});
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                module.exports = router;'