'use strict';
const express = require('express');
const router = express.Router();
const pool = require('../../memory/db/pool');

// GET /api/dashboard/ceo
// Phase F.2 - Single aggregated CEO dashboard endpoint
// All 20 queries run in parallel via Promise.allSettled - zero N+1
// Every field backed by production database - no mocked data
router.get('/ceo', async function(req, res) {
  var now = new Date();
    try {
        var results = await Promise.allSettled([
              // 0: Executive KPIs
                    pool.query("SELECT (SELECT COUNT(*) FROM lead_memory) as total_leads,(SELECT COUNT(*) FROM lead_memory WHERE created_at>=CURRENT_DATE) as leads_today,(SELECT COUNT(*) FROM lead_memory WHERE created_at>=date_trunc('week',CURRENT_DATE)) as leads_this_week,(SELECT COUNT(*) FROM lead_memory WHERE created_at>=date_trunc('month',CURRENT_DATE)) as leads_this_month,(SELECT COUNT(*) FROM lead_qualification WHERE category='hot') as hot_leads,(SELECT COUNT(*) FROM lead_qualification WHERE calculation_status='completed') as qualified_leads,(SELECT COUNT(*) FROM ai_decisions WHERE created_at>=CURRENT_DATE) as ai_decisions_today,(SELECT COUNT(*) FROM conversation_analysis WHERE created_at>=CURRENT_DATE) as active_conversations_today"),
                          // 1: Hot leads top 20
                                pool.query("SELECT lm.id,lm.full_name,lm.brand_name,lm.phone,lm.email,lm.source,lm.created_at,lq.category,lq.onboarding_probability,lq.score,lq.confidence_score,lq.assigned_rep FROM lead_memory lm LEFT JOIN lead_qualification lq ON lq.lead_memory_id=lm.id WHERE lq.category='hot' ORDER BY lq.score DESC NULLS LAST,lq.onboarding_probability DESC NULLS LAST LIMIT 20"),
                                      // 2: Channel health by source
                                            pool.query("SELECT source,COUNT(*) as total_leads,COUNT(*) FILTER(WHERE lq.category='hot') as hot,COUNT(*) FILTER(WHERE lq.category='warm') as warm,COUNT(*) FILTER(WHERE lq.category='cold') as cold FROM lead_memory lm LEFT JOIN lead_qualification lq ON lq.lead_memory_id=lm.id GROUP BY source ORDER BY total_leads DESC"),
                                                  // 3: AI decisions breakdown
                                                        pool.query("SELECT action_type,status,COUNT(*) as count FROM ai_decisions GROUP BY action_type,status ORDER BY count DESC LIMIT 30"),
                                                              // 4: Live activity feed
                                                                    pool.query("SELECT le.id,le.event_type,le.payload,le.created_at,lm.full_name,lm.brand_name,lm.source FROM lead_events le LEFT JOIN lead_memory lm ON lm.id=le.lead_memory_id ORDER BY le.created_at DESC LIMIT 30"),
                                                                          // 5: AI leaderboard by source
                                                                                pool.query("SELECT lm.source,COUNT(*) as total,COUNT(*) FILTER(WHERE lq.category='hot') as hot,COUNT(*) FILTER(WHERE lq.category='warm') as warm,COUNT(*) FILTER(WHERE lq.category IS NOT NULL) as qualified,AVG(lq.onboarding_probability) as avg_probability,AVG(lq.confidence_score) as avg_confidence FROM lead_memory lm LEFT JOIN lead_qualification lq ON lq.lead_memory_id=lm.id GROUP BY lm.source ORDER BY hot DESC"),
                                                                                      // 6: Funnel stages
                                                                                            pool.query("SELECT category,COUNT(*) as count FROM lead_qualification GROUP BY category ORDER BY CASE category WHEN 'hot' THEN 1 WHEN 'warm' THEN 2 WHEN 'cold' THEN 3 WHEN 'dead' THEN 4 ELSE 5 END"),
                                                                                                  // 7: Platform alerts
                                                                                                        pool.query("SELECT module_name,error_type,severity,message,created_at FROM platform_errors WHERE resolution_status='open' ORDER BY CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END,created_at DESC LIMIT 20"),
                                                                                                              // 8: Agent status
                                                                                                                    pool.query("SELECT agent_name,status,last_run_at,runs_completed,runs_failed,avg_runtime_ms,last_error FROM agent_performance ORDER BY agent_name"),
                                                                                                                          // 9: Queue status
                                                                                                                                pool.query("SELECT queue_name,status,pending_jobs,running_jobs,completed_jobs,failed_jobs,worker_count,avg_processing_time_ms FROM platform_queue_status ORDER BY queue_name"),
                                                                                                                                      // 10: Learning stats
                                                                                                                                            pool.query("SELECT COUNT(*) as total_predictions,COUNT(*) FILTER(WHERE evaluation_status='evaluated') as evaluated,COUNT(*) FILTER(WHERE created_at>=CURRENT_DATE) as today,AVG(confidence) as avg_confidence,COUNT(*) FILTER(WHERE evaluation_status='evaluated' AND outcome_matched=true) as correct FROM ai_predictions"),
                                                                                                                                                  // 11: Cost today by module
                                                                                                                                                        pool.query("SELECT module_name,SUM(cost_usd) as total_cost,SUM(tokens_input+tokens_output) as total_tokens,COUNT(*) as calls,AVG(latency_ms) as avg_latency FROM platform_cost_events WHERE created_at>=CURRENT_DATE GROUP BY module_name ORDER BY total_cost DESC"),
                                                                                                                                                              // 12: Conversation stats by channel
                                                                                                                                                                    pool.query("SELECT lm.source,COUNT(ca.id) as conversations,AVG(ca.confidence_score) as avg_confidence,AVG(ca.sentiment_score) as avg_sentiment FROM conversation_analysis ca LEFT JOIN lead_memory lm ON lm.id=ca.lead_memory_id WHERE ca.analysis_status='completed' GROUP BY lm.source"),
                                                                                                                                                                          // 13: SalesIQ chats
                                                                                                                                                                                pool.query("SELECT COUNT(*) as total_chats,COUNT(*) FILTER(WHERE created_at>=CURRENT_DATE) as today_chats,COUNT(*) FILTER(WHERE status='open') as open_chats FROM salesiq_chats"),
                                                                                                                                                                                      // 14: DLQ production
                                                                                                                                                                                            pool.query("SELECT job_type,COUNT(*) as count,MAX(created_at) as last_failure FROM job_dead_letter WHERE job_type NOT LIKE 'chaos%' GROUP BY job_type ORDER BY count DESC"),
                                                                                                                                                                                                  // 15: Module health latest
                                                                                                                                                                                                        pool.query("SELECT DISTINCT ON(module_name) module_name,status,health_score,checked_at as last_checked_at FROM platform_module_health ORDER BY module_name,checked_at DESC"),
                                                                                                                                                                                                              // 16: Workflow stats
                                                                                                                                                                                                                    pool.query("SELECT status,COUNT(*) as count FROM workflow_execution GROUP BY status"),
                                                                                                                                                                                                                          // 17: Revenue forecast
                                                                                                                                                                                                                                pool.query("SELECT forecast_value,forecast_date,scenario,confidence_score,created_at FROM revenue_forecasts ORDER BY created_at DESC LIMIT 5"),
                                                                                                                                                                                                                                      // 18: Copilot last insight
                                                                                                                                                                                                                                            pool.query("SELECT question,answer_summary,confidence_score,created_at FROM copilot_messages WHERE role='assistant' ORDER BY created_at DESC LIMIT 1"),
                                                                                                                                                                                                                                                  // 19: Lead time breakdown
                                                                                                                                                                                                                                                        pool.query("SELECT (SELECT COUNT(*) FROM lead_memory WHERE created_at>=CURRENT_DATE) as today,(SELECT COUNT(*) FROM lead_memory WHERE created_at>=CURRENT_DATE-INTERVAL '7 days') as last_7d,(SELECT COUNT(*) FROM lead_memory WHERE created_at>=CURRENT_DATE-INTERVAL '30 days') as last_30d,(SELECT COUNT(*) FROM lead_memory) as all_time")
                                                                                                                                                                                                                                                            ]);

                                                                                                                                                                                                                                                                function safe(i){return results[i].status==='fulfilled'?results[i].value.rows:[];}
                                                                                                                                                                                                                                                                    function safeOne(i){return results[i].status==='fulfilled'&&results[i].value.rows.length>0?results[i].value.rows[0]:{};}

                                                                                                                                                                                                                                                                        var kpis=safeOne(0),hotLeads=safe(1),channelRaw=safe(2),decisions=safe(3),activityFeed=safe(4);
                                                                                                                                                                                                                                                                            var aiLeaderboard=safe(5),funnel=safe(6),alerts=safe(7),agents=safe(8),queues=safe(9);
                                                                                                                                                                                                                                                                                var learning=safeOne(10),costs=safe(11),convByChannel=safe(12),salesiq=safeOne(13),dlq=safe(14);
                                                                                                                                                                                                                                                                                    var modules=safe(15),workflows=safe(16),forecasts=safe(17),copilotInsight=safeOne(18),leadTime=safeOne(19);

                                                                                                                                                                                                                                                                                        var channelMap={};channelRaw.forEach(function(r){channelMap[r.source]=r;});
                                                                                                                                                                                                                                                                                            var convMap={};convByChannel.forEach(function(r){convMap[r.source]=r;});

                                                                                                                                                                                                                                                                                                var aiChannelDefs=[
                                                                                                                                                                                                                                                                                                      {channel:'Meta AI',sources:['meta','meta_ad','facebook','Meta','META']},
                                                                                                                                                                                                                                                                                                            {channel:'SalesIQ AI',sources:['salesiq','website','chat','SalesIQ','Website','SALESIQ']},
                                                                                                                                                                                                                                                                                                                  {channel:'Retell AI',sources:['retell','call','phone','Retell','RETELL']},
                                                                                                                                                                                                                                                                                                                        {channel:'Email AI',sources:['email','Email','EMAIL']},
                                                                                                                                                                                                                                                                                                                              {channel:'SMS AI',sources:['sms','twilio','SMS','Twilio','TWILIO']}
                                                                                                                                                                                                                                                                                                                                  ];

                                                                                                                                                                                                                                                                                                                                      var aiChannelHealth=aiChannelDefs.map(function(ch){
                                                                                                                                                                                                                                                                                                                                            var td=0,hot=0,warm=0,cold=0,convs=0,conf=null;
                                                                                                                                                                                                                                                                                                                                                  ch.sources.forEach(function(s){
                                                                                                                                                                                                                                                                                                                                                          if(channelMap[s]){td+=parseInt(channelMap[s].total_leads||0);hot+=parseInt(channelMap[s].hot||0);warm+=parseInt(channelMap[s].warm||0);cold+=parseInt(channelMap[s].cold||0);}
                                                                                                                                                                                                                                                                                                                                                                  if(convMap[s]){convs+=parseInt(convMap[s].conversations||0);if(convMap[s].avg_confidence)conf=parseFloat(convMap[s].avg_confidence);}
                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                              return {channel:ch.channel,status:td>0?'active':'no_data',total_leads:td,hot_leads:hot,warm_leads:warm,cold_leads:cold,conversations:convs,qualified:hot+warm,conversion_pct:td>0?Math.round((hot+warm)/td*1000)/10:0,avg_confidence:conf};
                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                      var copilotItems=[];
                                                                                                                                                                                                                                                                                                                                                                                          if(parseInt(kpis.hot_leads)>0)copilotItems.push(parseInt(kpis.hot_leads)+' hot leads require attention today');
                                                                                                                                                                                                                                                                                                                                                                                              if(parseInt(kpis.ai_decisions_today)>0)copilotItems.push(parseInt(kpis.ai_decisions_today)+' AI decisions made today');
                                                                                                                                                                                                                                                                                                                                                                                                  if(parseInt(kpis.leads_today)>0)copilotItems.push(parseInt(kpis.leads_today)+' new leads captured today');
                                                                                                                                                                                                                                                                                                                                                                                                      if(alerts.length>0)copilotItems.push(alerts.length+' platform alert(s) require attention');
                                                                                                                                                                                                                                                                                                                                                                                                          var openDlq=dlq.reduce(function(s,r){return s+parseInt(r.count||0);},0);
                                                                                                                                                                                                                                                                                                                                                                                                              if(openDlq>0)copilotItems.push(openDlq+' production jobs in dead letter queue');
                                                                                                                                                                                                                                                                                                                                                                                                                  if(costs.length>0){var tc=costs.reduce(function(s,r){return s+parseFloat(r.total_cost||0);},0);if(tc>0)copilotItems.push("Today's AI cost: $"+tc.toFixed(4));}
                                                                                                                                                                                                                                                                                                                                                                                                                      if(copilotItems.length===0)copilotItems.push('Platform operating normally - no immediate actions required');

                                                                                                                                                                                                                                                                                                                                                                                                                          res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                success:true,retrieved_at:now.toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                      kpis:{
                                                                                                                                                                                                                                                                                                                                                                                                                                              total_leads:parseInt(kpis.total_leads||0),leads_today:parseInt(kpis.leads_today||0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                      leads_this_week:parseInt(kpis.leads_this_week||0),leads_this_month:parseInt(kpis.leads_this_month||0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                              hot_leads:parseInt(kpis.hot_leads||0),qualified_leads:parseInt(kpis.qualified_leads||0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ai_decisions_today:parseInt(kpis.ai_decisions_today||0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              active_conversations_today:parseInt(kpis.active_conversations_today||0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      salesiq_open_chats:parseInt(salesiq.open_chats||0),lead_time:leadTime
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  hot_leads:hotLeads,ai_channel_health:aiChannelHealth,channel_raw:channelRaw,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        activity_feed:activityFeed,ai_leaderboard:aiLeaderboard,funnel:funnel,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alerts:alerts,agents:agents,queues:queues,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    learning:{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            total_predictions:parseInt(learning.total_predictions||0),evaluated:parseInt(learning.evaluated||0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    today:parseInt(learning.today||0),avg_confidence:parseFloat(learning.avg_confidence||0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            correct:parseInt(learning.correct||0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    accuracy:parseInt(learning.evaluated)>0?Math.round(parseInt(learning.correct)/parseInt(learning.evaluated)*1000)/10:0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                costs:costs,decisions:decisions,modules:modules,workflows:workflows,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      forecasts:forecasts,copilot_briefing:copilotItems,copilot_last_insight:copilotInsight,dlq:dlq
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }catch(err){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('[CEO Dashboard]',err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({success:false,error:err.message});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      module.exports = router;