-- Phase 4: Autonomous AI Revenue Operations -- Migration 020
CREATE TABLE IF NOT EXISTS agent_runs (run_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), agent_name VARCHAR(100) NOT NULL, run_type VARCHAR(50) NOT NULL DEFAULT 'scheduled', status VARCHAR(30) NOT NULL DEFAULT 'running', started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), completed_at TIMESTAMPTZ, duration_ms INTEGER, findings_count INTEGER DEFAULT 0, recommendations_count INTEGER DEFAULT 0, actions_triggered INTEGER DEFAULT 0, error_message TEXT, metadata JSONB DEFAULT '{}');
CREATE INDEX IF NOT EXISTS idx_agent_runs_name_started ON agent_runs(agent_name, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_runs_status ON agent_runs(status);
CREATE TABLE IF NOT EXISTS agent_recommendations (rec_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), run_id UUID REFERENCES agent_runs(run_id) ON DELETE SET NULL, agent_name VARCHAR(100) NOT NULL, rec_type VARCHAR(100) NOT NULL, title VARCHAR(500) NOT NULL, description TEXT NOT NULL, evidence JSONB DEFAULT '[]', reasoning TEXT, confidence NUMERIC(5,2) DEFAULT 0, affected_lead_id UUID, affected_resource JSONB DEFAULT '{}', recommended_action TEXT, expected_impact TEXT, priority VARCHAR(20) DEFAULT 'medium', status VARCHAR(30) DEFAULT 'open', prediction_id UUID, workflow_id UUID, approved_by VARCHAR(200), actioned_at TIMESTAMPTZ, expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_agent_recs_agent_status ON agent_recommendations(agent_name, status);
CREATE INDEX IF NOT EXISTS idx_agent_recs_priority ON agent_recommendations(priority, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_recs_lead ON agent_recommendations(affected_lead_id);
CREATE TABLE IF NOT EXISTS agent_decisions (decision_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), run_id UUID REFERENCES agent_runs(run_id) ON DELETE SET NULL, rec_id UUID REFERENCES agent_recommendations(rec_id) ON DELETE SET NULL, agent_name VARCHAR(100) NOT NULL, action_type VARCHAR(100) NOT NULL, action_payload JSONB DEFAULT '{}', rationale TEXT, confidence NUMERIC(5,2) DEFAULT 0, is_autonomous BOOLEAN DEFAULT FALSE, requires_approval BOOLEAN DEFAULT TRUE, approved_by VARCHAR(200), approved_at TIMESTAMPTZ, executed_at TIMESTAMPTZ, outcome JSONB DEFAULT '{}', is_reversible BOOLEAN DEFAULT TRUE, reversed_at TIMESTAMPTZ, reversed_by VARCHAR(200), audit_trail JSONB DEFAULT '[]', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS agent_performance (perf_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), agent_name VARCHAR(100) NOT NULL, period_start TIMESTAMPTZ NOT NULL, period_end TIMESTAMPTZ NOT NULL, total_runs INTEGER DEFAULT 0, successful_runs INTEGER DEFAULT 0, total_recommendations INTEGER DEFAULT 0, actioned_recommendations INTEGER DEFAULT 0, action_rate NUMERIC(5,4) DEFAULT 0, avg_confidence NUMERIC(5,2) DEFAULT 0, avg_duration_ms INTEGER DEFAULT 0, business_impact_score NUMERIC(5,2) DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_agent_perf_name_period ON agent_performance(agent_name, period_start DESC);