'use strict';
const ZohoIngestor=require('../ingestors/zoho.ingestor');
const RetellIngestor=require('../ingestors/retell.ingestor');
const SalesIQIngestor=require('../ingestors/salesiq.ingestor');
const EmailIngestor=require('../ingestors/email.ingestor');
const TaskIngestor=require('../ingestors/task.ingestor');
const INGEST_TYPES={ZOHO_NEW_LEAD:'zoho.new_lead',ZOHO_LEAD_UPDATE:'zoho.lead_update',ZOHO_TASK_CREATED:'zoho.task_created',ZOHO_TASK_UPDATED:'zoho.task_updated',ZOHO_NOTE_ADDED:'zoho.note_added',RETELL_CALL_STARTED:'retell.call_started',RETELL_CALL_ENDED:'retell.call_ended',RETELL_CALL_ANALYZED:'retell.call_analyzed',SALESIQ_CHAT_STARTED:'salesiq.chat_started',SALESIQ_CHAT_ENDED:'salesiq.chat_ended',EMAIL_SENT:'email.sent',EMAIL_OPENED:'email.opened',EMAIL_REPLIED:'email.replied',FOLLOWUP_CREATED:'followup.created',FOLLOWUP_COMPLETED:'followup.completed'};
async function ingest(type,payload){switch(type){case INGEST_TYPES.ZOHO_NEW_LEAD:return ZohoIngestor.ingestNewLead(payload);case INGEST_TYPES.ZOHO_LEAD_UPDATE:return ZohoIngestor.ingestLeadUpdate(payload);case INGEST_TYPES.ZOHO_TASK_CREATED:return ZohoIngestor.ingestTask(payload,'created');case INGEST_TYPES.ZOHO_TASK_UPDATED:return ZohoIngestor.ingestTask(payload,'updated');case INGEST_TYPES.ZOHO_NOTE_ADDED:return ZohoIngestor.ingestNote(payload);case INGEST_TYPES.RETELL_CALL_STARTED:return RetellIngestor.ingestCallStarted(payload);case INGEST_TYPES.RETELL_CALL_ENDED:return RetellIngestor.ingestCallEnded(payload);case INGEST_TYPES.RETELL_CALL_ANALYZED:return RetellIngestor.ingestCallAnalyzed(payload);case INGEST_TYPES.SALESIQ_CHAT_STARTED:return SalesIQIngestor.ingestChatStarted(payload);case INGEST_TYPES.SALESIQ_CHAT_ENDED:return SalesIQIngestor.ingestChatEnded(payload);case INGEST_TYPES.EMAIL_SENT:return EmailIngestor.ingestEmailSent(payload);case INGEST_TYPES.EMAIL_OPENED:return EmailIngestor.ingestEmailOpened(payload);case INGEST_TYPES.EMAIL_REPLIED:return EmailIngestor.ingestEmailReplied(payload);case INGEST_TYPES.FOLLOWUP_CREATED:return TaskIngestor.ingestFollowUp({...payload,status:'pending'});case INGEST_TYPES.FOLLOWUP_COMPLETED:return TaskIngestor.ingestFollowUp({...payload,status:'completed'});default:throw new Error('MemoryService: unknown type "'+type+'"');}}
module.exports={ingest,INGEST_TYPES};
