'use strict';
const pool=require('../db/pool');
const EMAIL_DIRECTION={INBOUND:'inbound',OUTBOUND:'outbound'};
const EMAIL_STATUS={SENT:'sent',DELIVERED:'delivered',OPENED:'opened',CLICKED:'clicked',REPLIED:'replied',BOUNCED:'bounced',FAILED:'failed'};
async function create(d,client){const db=client||pool;const{lead_memory_id,zoho_lead_id,source_id=null,conversation_id=null,direction=EMAIL_DIRECTION.OUTBOUND,status=EMAIL_STATUS.SENT,from_address,to_address,subject=null,body_preview=null,sent_at=new Date(),opened_at=null,replied_at=null,sales_executive_id=null,sales_executive_name=null,raw_payload={}}=d;const r=await db.query('INSERT INTO email_events (lead_memory_id,zoho_lead_id,source_id,conversation_id,direction,status,from_address,to_address,subject,body_preview,sent_at,opened_at,replied_at,sales_executive_id,sales_executive_name,raw_payload) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *',[lead_memory_id,zoho_lead_id,source_id,conversation_id,direction,status,from_address,to_address,subject,body_preview,sent_at,opened_at,replied_at,sales_executive_id,sales_executive_name,JSON.stringify(raw_payload)]);return r.rows[0];}
async function updateBySourceId(sid,u){const allowed=['status','opened_at','replied_at','raw_payload'];const sets=[],params=[];let idx=1;for(const k of allowed){if(u[k]!==undefined){const v=k==='raw_payload'?JSON.stringify(u[k]):u[k];sets.push(k+'=$'+idx++);params.push(v);}}if(!sets.length)return null;params.push(sid);const r=await pool.query('UPDATE email_events SET '+sets.join(',')+',updated_at=NOW() WHERE source_id=$'+idx+' RETURNING *',params);return r.rows[0]||null;}
async function listByZohoId(z,o={}){const{limit=50,offset=0,direction=null}=o;const params=[z],filters=['zoho_lead_id=$1'];let idx=2;if(direction){filters.push('direction=$'+idx++);params.push(direction);}params.push(limit,offset);const r=await pool.query('SELECT * FROM email_events WHERE '+filters.join(' AND ')+' ORDER BY sent_at DESC LIMIT $'+idx+++' OFFSET $'+idx,params);return r.rows;}
async function existsBySourceId(sid){const r=await pool.query('SELECT id FROM email_events WHERE source_id=$1 LIMIT 1',[sid]);return r.rows.length>0;}
module.exports={EMAIL_DIRECTION,EMAIL_STATUS,create,updateBySourceId,listByZohoId,existsBySourceId};
