'use strict';
const pool=require('../db/pool');
async function findByZohoId(id){const r=await pool.query('SELECT * FROM lead_memory WHERE zoho_lead_id=$1 LIMIT 1',[id]);return r.rows[0]||null;}
async function findById(id){const r=await pool.query('SELECT * FROM lead_memory WHERE id=$1',[id]);return r.rows[0]||null;}
async function findByEmail(e){if(!e)return null;const r=await pool.query('SELECT * FROM lead_memory WHERE email=$1 LIMIT 1',[e]);return r.rows[0]||null;}
async function findByPhone(p){if(!p)return null;const r=await pool.query('SELECT * FROM lead_memory WHERE phone=$1 LIMIT 1',[p]);return r.rows[0]||null;}
async function create(data,client){const db=client||pool;const{zoho_lead_id,email=null,phone=null,full_name=null,company=null,pipeline_stage=null,lead_owner_id=null,lead_owner_name=null,crm_data={}}=data;const r=await db.query('INSERT INTO lead_memory (zoho_lead_id,email,phone,full_name,company,pipeline_stage,lead_owner_id,lead_owner_name,crm_data) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT (zoho_lead_id) DO UPDATE SET email=COALESCE(EXCLUDED.email,lead_memory.email),phone=COALESCE(EXCLUDED.phone,lead_memory.phone),full_name=COALESCE(EXCLUDED.full_name,lead_memory.full_name),updated_at=NOW() RETURNING *',[zoho_lead_id,email,phone,full_name,company,pipeline_stage,lead_owner_id,lead_owner_name,JSON.stringify(crm_data)]);return r.rows[0];}
async function syncFromCRM(zohoLeadId,data,client){const db=client||pool;const{email,phone,full_name,company,pipeline_stage,lead_owner_id,lead_owner_name,crm_data={}}=data;const r=await db.query('UPDATE lead_memory SET email=COALESCE($2,email),phone=COALESCE($3,phone),full_name=COALESCE($4,full_name),company=COALESCE($5,company),pipeline_stage=COALESCE($6,pipeline_stage),lead_owner_id=COALESCE($7,lead_owner_id),lead_owner_name=COALESCE($8,lead_owner_name),crm_data=$9,synced_at=NOW(),updated_at=NOW() WHERE zoho_lead_id=$1 RETURNING *',[zohoLeadId,email||null,phone||null,full_name||null,company||null,pipeline_stage||null,lead_owner_id||null,lead_owner_name||null,JSON.stringify(crm_data)]);return r.rows[0]||null;}
async function incrementCounter(zohoLeadId,field,client){const db=client||pool;const allowed=['call_count','email_count','chat_count'];if(!allowed.includes(field))throw new Error('Invalid counter: '+field);await db.query('UPDATE lead_memory SET '+field+'='+field+'+1,updated_at=NOW() WHERE zoho_lead_id=$1',[zohoLeadId]);}
async function touchLastContacted(zohoLeadId,ts,client){const db=client||pool;await db.query('UPDATE lead_memory SET last_contacted_at=$2,updated_at=NOW() WHERE zoho_lead_id=$1',[zohoLeadId,ts||new Date()]);}
async function markOnboarded(zohoLeadId,client){const db=client||pool;await db.query('UPDATE lead_memory SET is_onboarded=TRUE,onboarded_at=NOW(),updated_at=NOW() WHERE zoho_lead_id=$1',[zohoLeadId]);}
async function list(o={}){const{limit=50,offset=0,pipeline_stage=null,lead_owner_id=null,is_onboarded=null}=o;const params=[],filters=[];let idx=1;if(pipeline_stage){filters.push('pipeline_stage=$'+idx++);params.push(pipeline_stage);}if(lead_owner_id){filters.push('lead_owner_id=$'+idx++);params.push(lead_owner_id);}if(is_onboarded!==null){filters.push('is_onboarded=$'+idx++);params.push(is_onboarded);}params.push(limit,offset);const where=filters.length?'WHERE '+filters.join(' AND '):'';const r=await pool.query('SELECT * FROM lead_memory '+where+' ORDER BY updated_at DESC LIMIT $'+idx+++' OFFSET $'+idx,params);return r.rows;}
module.exports={findByZohoId,findById,findByEmail,findByPhone,create,syncFromCRM,incrementCounter,touchLastContacted,markOnboarded,list};
